String.prototype.hashCode = function() {
  var hash = 0, i, chr, len;
  if (this.length == 0) return hash;
  for (i = 0, len = this.length; i < len; i++) {
    chr   = this.charCodeAt(i);
    hash  = ((hash << 5) - hash) + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
};

var ids = {};
for(var i = 0; i < 100; i += 10){
  ids['1' + i] = '1' + i;
  ids['2' + i] = '2' + i;
  ids['3' + i] = '3' + i;
  ids['4' + i] = '4' + i;
}

var professorNames = [
  'Flores',
  'Mason',
  'Brooks',
  'Peterson',
  'Mendoza',
  'Welch',
  'Marshall',
  'Payne',
  'Bell',
  'Carroll',
  'Mills',
  'Ramos',
  'Pierce',
  'Knight',
  'Wells',
  'Vasquez',
  'Burns',
  'Cox',
  'Gomez',
  'Freeman',
  'Tucker',
  'Hernandez',
  'Burke',
  'Ferguson',
  'Murray',
  'Chapman',
  'Hall',
  'Montgomery',
  'Evans',
  'Schmidt',
  'Hansen',
  'Ruiz',
  'Price',
  'Harris',
  'Baker',
  'Ruiz',
  'Myers',
  'Rogers',
  'Pierce',
  'Kelly',
  'Cooper',
  'Warren',
  'King',
  'Fowler',
  'Bailey',
  'Stewart',
  'Brooks',
  'Daniels',
  'Riley',
  'Ford',
  'Moreno',
  'Gardner',
  'Olson',
  'Hamilton',
  'Schmidt',
  'Morales',
  'Morris',
  'Boyd',
  'Cook',
  'Johnston',
  'Freeman',
  'Carroll',
  'Barnes',
  'James',
  'Matthews',
  'Gibson',
  'Powell',
  'Boyd',
  'Marshall',
  'Weaver',
  'Evans',
  'Phillips',
  'Patterson',
  'Rose',
  'Rodriguez',
  'Hall',
  'Wilson',
  'Stone',
  'Butler',
  'Morrison',
  'Wood',
  'Ortiz',
  'Crawford',
  'Carroll',
  'Thompson',
  'Robertson',
  'Daniels',
  'Lopez',
  'Gordon',
  'Burke',
  'Griffin',
  'Patterson',
  'Martinez',
  'Martinez',
  'Rice',
  'Turner',
  'Wells',
  'Garcia',
  'Wood',
  'Lawrence',
  'Hansen',
  'Hicks',
  'Armstrong',
  'Wagner',
  'Scott',
  'Ramos',
  'Riley',
  'Hunt',
  'George',
  'Mason',
  'Mitchell',
  'Griffin',
  'Mills',
  'Marshall',
  'Rivera',
  'Fernandez',
  'Perez',
  'Andrews',
  'Clark',
  'Murray',
  'Kennedy',
  'Stone',
  'Romero',
  'Simpson',
  'Lewis',
  'Grant',
  'Castillo',
  'Dixon',
  'Gonzalez',
  'Murray',
  'Porter',
  'Richards',
  'Fowler',
  'Moore',
  'Ray',
  'Carter',
  'Mendoza',
  'Hughes',
  'Martinez',
  'Wagner',
  'Willis',
  'Wells',
  'Palmer',
  'Willis',
  'Morales',
  'Peterson',
  'Roberts',
  'Rivera',
  'Olson',
  'Schmidt',
  'Fuller',
  'Nelson',
  'Harvey',
  'Simmons',
  'Arnold',
  'Collins',
  'Stevens',
  'Owens',
  'Willis',
  'Morgan',
  'Grant',
  'Graham',
  'Payne',
  'Greene',
  'Phillips',
  'Carpenter',
  'Torres',
  'Woods',
  'Martinez',
  'Mcdonald',
  'Bailey',
  'Howard',
  'Robertson',
  'Gonzales',
  'Ramirez',
  'Sanders',
  'Davis',
  'Boyd',
  'Johnson',
  'Boyd',
  'Hudson',
  'Castillo',
  'Campbell',
  'Reed',
  'Fowler',
  'Schmidt',
  'Wells',
  'Chavez',
  'Rodriguez',
  'Mitchell',
  'Peters',
  'Lynch',
  'Mcdonald',
  'Torres',
  'Moreno',
  'Bennett',
  'Myers',
  'Hicks',
  'George',
  'Hanson',
  'Payne',
  'Lee',
  'Wells',
  'Jones',
  'Franklin',
  'Peterson',
  'Richards',
  'Carroll',
  'Ford',
  'Fernandez',
  'Stone',
  'Stanley',
  'Spencer',
  'Chapman',
  'Flores',
  'King',
  'Murray',
  'Mason',
  'Robertson',
  'Harper',
  'Watson',
  'Sanders',
  'Fisher',
  'Lawson',
  'Harrison',
  'Wagner',
  'Rivera',
  'Mitchell',
  'Owens',
  'Nguyen',
  'Hayes',
  'Porter',
  'Baker',
  'Hunter',
  'Willis',
  'Berry',
  'Warren',
  'Jordan',
  'Cruz',
  'Hamilton',
  'Evans',
  'Wright',
  'Kim',
  'Carroll',
  'Baker',
  'Lopez',
  'Hall',
  'Kelley',
  'Allen',
  'Wheeler',
  'Franklin',
  'Rivera',
  'Long',
  'Hart',
  'Gonzalez',
  'Hamilton',
  'Bowman',
  'Marshall',
  'Alexander',
  'Medina',
  'Larson',
  'Pierce',
  'Morrison',
  'Ortiz',
  'Kelley',
  'Sims',
  'Mitchell',
  'Griffin',
  'Morgan',
  'Lawson',
  'Harper',
  'Myers',
  'Garcia',
  'Gray',
  'Martin',
  'Murphy',
  'Walker',
  'Jackson',
  'Chavez',
  'Harper',
  'Vasquez',
  'Mendoza',
  'Daniels',
  'Hicks',
  'Jenkins',
  'Grant',
  'Flores',
  'Freeman',
  'White',
  'Long',
  'Peters',
  'Hill',
  'Bishop',
  'Daniels',
  'Cox',
  'Lewis',
  'Powell',
  'George',
  'Rodriguez',
  'Garrett',
  'Rose',
  'Alexander',
  'Powell',
  'Morgan',
  'Ruiz',
  'Pierce',
  'Hansen',
  'Palmer',
  'Ellis',
  'Ramos',
  'Thompson',
  'Howell',
  'Powell',
  'Daniels',
  'Dunn',
  'Allen',
  'Long',
  'Vasquez',
  'Martin',
  'Payne',
  'Wright',
  'Gardner',
  'Miller',
  'Romero',
  'Robinson',
  'Spencer',
  'Mitchell',
  'Porter',
  'Kim',
  'Mason',
  'Hart',
  'Grant',
  'Thomas',
  'Burns',
  'Watkins',
  'Schmidt',
  'Fisher',
  'Moore',
  'Williamson',
  'Bryant',
  'Gordon',
  'Taylor',
  'Murphy',
  'Oliver',
  'Diaz',
  'Greene',
  'Stephens',
  'Cunningham'
];

var times = [
  { time: '8:00am - 8:50am', duration: 50 },
  { time: '9:00am - 9:50am', duration: 50 },
  { time: '10:00am - 10:50am', duration: 50 },
  { time: '11:00am - 11:50am', duration: 50 },
  { time: '12:00pm - 12:50pm', duration: 50 },
  { time: '8:00am - 9:15am', duration: 75 },
  { time: '9:00am - 10:15am', duration: 75 },
  { time: '10:00am - 11:15am', duration: 75 },
  { time: '11:00am - 12:15pm', duration: 75 },
  { time: '12:00pm - 1:15pm', duration: 75 },
  { time: '8:30am - 9:45am', duration: 75 },
  { time: '9:30am - 10:45am', duration: 75 },
  { time: '10:30am - 11:45am', duration: 75 },
  { time: '11:30am - 12:45pm', duration: 75 },
  { time: '12:30pm - 1:45pm', duration: 75 },
  { time: '1:00pm - 2:15pm', duration: 75 },
  { time: '2:00pm - 3:15pm', duration: 75 },
  { time: '3:00pm - 4:15pm', duration: 75 },
  { time: '4:00pm - 5:15pm', duration: 75 },
  { time: '5:00pm - 1:15pm', duration: 75 },
  { time: '1:30pm - 2:45pm', duration: 75 },
  { time: '2:30pm - 3:45pm', duration: 75 },
  { time: '3:30pm - 4:45pm', duration: 75 },
  { time: '4:30pm - 5:45pm', duration: 75 },
  { time: '5:30pm - 1:45pm', duration: 75 }
];

var majors = {
  'MATH': 'MATH',
  'CPSC': 'CPSC',
  'ECON': 'ECON',
  'MGMT': 'MGMT',
  'ACTG': 'ACTG',
  'FIN': 'FIN',
  'MGSC': 'MGSC',
  'SE': 'SE',
  'PHYS': 'PHYS',
  'CHEM': 'CHEM',
  'ENG': 'ENG',
  'BUS': 'BUS',
  'MKTG': 'MKTG',
  'KINE': 'KINE',
  'ART': 'ART',
  'HIST': 'HIST',
  'DANC': 'DANC',
  'PSY': 'PSY',
  'SOC': 'SOC',
  'BIO': 'BIO',
  'FTV': 'FTV',
};

var courses = [];

var fs = require('fs');

for(var k in majors){
  for(var id in ids){
    var professorName = professorNames[randomInt(0, professorNames.length)],
     classTime = times[randomInt(0, times.length)],
     availableSpots = randomInt(0, 30);
    var c = {
      id: id,
      course: k,
      professorName: professorName,
      professorId: Math.abs(professorName.hashCode()),
      time: classTime.time,
      duration: classTime.duration,
      totalSpots: 30,
      availableSpots: availableSpots
    };
    if(availableSpots == 0)
      c.waitlist = randomInt(0, 15);
    courses.push(c);
  }
}

fs.writeFile(__dirname + '/courses.json', JSON.stringify(courses), function(err) {
  if(err) {
      console.log(err);
  } else {
      console.log("Courses saved!");
  }
});



function randomInt (low, high) {
  return Math.floor(Math.random() * (high - low) + low);
}










